name: main build

on:
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm lint
      - run: pnpm tsc
      # - run: pnpm eslint .
      # - run: pnpm prettier -c **/*.ts
